version: '3.8'

services:
  client:
    build: .
    container_name: kpi_client
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true

networks:
  kpi_network:
    external: true 